---

# features.mysql or features.postgresql should be true

# Download & install
- include: install.yml

# setup smoke tests
- include: goss.yml

# Database configuration, one or another
- include: postgresql.yml
  when: artifactory_database == 'postgresql'

- include: mysql.yml
  when: artifactory_database == 'mysql'

- include: derby.yml
  when: artifactory_database == 'derby'
